#!/bin/bash
set -e

apt-get update
apt-get install -y tmux git wget bzr

ARCH="amd64"
OS="linux"
VERSION="1.4.1"
GOVERSION="go${VERSION}.${OS}-${ARCH}"
GOTAR="${GOVERSION}.tar.gz"
LOCATION="https://storage.googleapis.com/golang/${GOTAR}"

juju-log "Downloading ${GOTAR} from ${LOCATION}"

wget "$LOCATION" -O "/tmp/${GOTAR}"
[[ -d /usr/local/go ]] && rm -rf /usr/local/go

juju-log "Extracting ${GOTAR}"

tar -C /usr/local -xvzf "/tmp/${GOTAR}"
[[ ":$PATH:" == *":/usr/local/go/bin:"* ]] || export PATH=$PATH:/usr/local/go/bin

export GOPATH=/root/go
[[ ":$PATH:" == *":${GOPATH}/bin:"* ]] || export PATH=${GOPATH}/bin:$PATH

juju-log "Getting Mindfork dependencies and building"

go get -u -v -d github.com/mindfork/mindfork
go get -u -v launchpad.net/godeps/...
pushd ${GOPATH}/src/github.com/mindfork/mindfork/
godeps -u dependencies.tsv
go clean -i ./...
go install ./...
popd

ln -sf ${GOPATH}/bin/mindforkd /usr/local/bin/mindforkd

juju-log "Writing config file"

MF_PORT=$(config-get port)
config_template_location="/etc/mindfork/mindfork.toml"
[[ -d /etc/mindfork ]] || mkdir -p /etc/mindfork
cat <<EOF > $config_template_location
port = ${MF_PORT}
EOF

# juju-log "Writing service file"
# [[ -d /usr/lib/systemd/system ]] || mkdir -p /usr/lib/systemd/system
# cp files/mindfork.service /usr/lib/systemd/system/mindfork.service
# systemctl daemon-reload

# juju-log "Enabling service"
# systemctl enable mindfork.service
