#!/bin/bash

set -e 

export GOPATH=/root/go

mfpath=${GOPATH}/src/github.com/mindfork/mindfork
[[ ":$PATH:" == *":/usr/local/go/bin:"* ]] || export PATH=$PATH:/usr/local/go/bin
[[ ":$PATH:" == *":${GOPATH}/bin:"* ]] || export PATH=${GOPATH}/bin:$PATH

juju-log "Getting latest Mindfork upstream"

[[ -d ${GOPATH} ]] && rm -rf ${mfpath}
go get -u -v -d github.com/mindfork/mindfork/...
pushd ${GOPATH}/src/github.com/mindfork/mindfork
git remote add upstream $(config-get remote)
git checkout $(config-get version)
go clean -i ./...
go get -u -v launchpad.net/godeps/...
godeps -u dependencies.tsv
go install ./...
popd

[[ -f /usr/local/bin/mindforkd ]] && rm /usr/local/bin/mindforkd
ln -sf ${GOPATH}/bin/mindforkd /usr/local/bin/mindforkd

juju-log "Restarting Mindfork service"

if [[ -f /var/run/mindforkd ]]; then
  juju-log "Stopping Mindfork daemon"
  start-stop-daemon --stop --pid /var/run/mindforkd
  juju-log "Starting Mindfork daemon"
  start-stop-daemon \
	  --start \
	  --background \
	  --make-pidfile --pidfile /var/run/mindforkd.pid \
	  --exec /usr/local/bin/mindforkd # -- $PROGRAM-ARGUMENT
fi

# service mindfork restart

# juju-log "Writing service file"
# [[ -d /usr/lib/systemd/system ]] || mkdir -p /usr/lib/systemd/system
# cp files/mindfork.service /usr/lib/systemd/system/mindfork.service
# systemctl daemon-reload

# juju-log "Enabling service"
# systemctl enable mindfork.service
