#!/bin/bash
set -e 

export GOPATH=/root/go

/usr/local/go/bin/go get -u -v -d github.com/mindfork/mindfork/...
pushd ${GOPATH}/src/github.com/mindfork/mindfork
git fetch --all

ref=$(action-get version)
if [[ $ref != "tip" ]]; then
  git checkout $ref
fi

/usr/local/go/bin/go clean -i ./...
/usr/local/go/bin/go install ./...
ln -sf ${GOPATH}/bin/mindforkd /usr/local/bin/mindforkd 

if [[ -f /var/run/mindforkd.pid ]]; then
  start-stop-daemon --stop --pid /var/run/mindforkd.pid
  start-stop-daemon \
  	--start \
	--background \
	--make-pidfile --pidfile /var/run/mindforkd.pid \
	--exec $(which mindforkd)
fi

popd
